site_name: My Project Template
site_description: This is just an example 
repo_name: My Project Template
repo_url: https://github.com/Rellotscrewdriver/my-project-template

theme:
  #logo: material/library
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

extra:
 social:
   - icon: fontawesome/brands/discord 
     link: https://discord.com/users/481829350749110293
     name: Follow Rellotscrewdriver on Discord
     generator: false

copyright: Copyright &copy; 2025 Rellotscrewdriver

